name: Integration tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]


jobs:
  integration-tests:
    name: Build and run integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run integration tests with pytest
      run: |
        pytest -m "integration_test or slow_integration_test"
