name: Integration tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]


jobs:
  integration-tests:
    name: Build and run integration tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run (quick) integration tests
      run: |
        pytest -v tests/ -m "integration_test"
    # - name: Run slow integration tests
    #  run: |
    #    pytest -v tests/ -m "slow_integration_test"
